--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/etc/nixos/nixos-config/Wallpaper"

-- Special
background="#25243e"
foreground="#e8cac0"
cursor="#e8cac0"

-- Colors
color0="#25243e"
color1="#435BB1"
color2="#5566A5"
color3="#4D75CC"
color4="#9C738F"
color5="#5686D5"
color6="#5A8FE6"
color7="#e8cac0"
color8="#a28d86"
color9="#435BB1"
color10="#5566A5"
color11="#4D75CC"
color12="#9C738F"
color13="#5686D5"
color14="#5A8FE6"
color15="#e8cac0"
