--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/joe/Configs/Wallpaper"

-- Special
background="#0C1419"
foreground="#d8d5bf"
cursor="#d8d5bf"

-- Colors
color0="#0C1419"
color1="#9E5531"
color2="#CC6F36"
color3="#9E6D4C"
color4="#678E78"
color5="#E1A35A"
color6="#D5B064"
color7="#d8d5bf"
color8="#979585"
color9="#9E5531"
color10="#CC6F36"
color11="#9E6D4C"
color12="#678E78"
color13="#E1A35A"
color14="#D5B064"
color15="#d8d5bf"
