# Shell variables
# Generated by 'wal'
wallpaper='/home/joe/Configs/Wallpaper'

# Special
background='#0C1419'
foreground='#d8d5bf'
cursor='#d8d5bf'

# Colors
color0='#0C1419'
color1='#9E5531'
color2='#CC6F36'
color3='#9E6D4C'
color4='#678E78'
color5='#E1A35A'
color6='#D5B064'
color7='#d8d5bf'
color8='#979585'
color9='#9E5531'
color10='#CC6F36'
color11='#9E6D4C'
color12='#678E78'
color13='#E1A35A'
color14='#D5B064'
color15='#d8d5bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
