--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/etc/nixos/nixos-config/Wallpaper"

-- Special
background="#0c121a"
foreground="#d8c8bc"
cursor="#d8c8bc"

-- Colors
color0="#0c121a"
color1="#D3A979"
color2="#697988"
color3="#987780"
color4="#58949F"
color5="#46A8AF"
color6="#62B2B1"
color7="#d8c8bc"
color8="#978c83"
color9="#D3A979"
color10="#697988"
color11="#987780"
color12="#58949F"
color13="#46A8AF"
color14="#62B2B1"
color15="#d8c8bc"
