# Shell variables
# Generated by 'wal'
wallpaper='/home/joe/Configs/Wallpaper'

# Special
background='#0A0101'
foreground='#ddd2cb'
cursor='#ddd2cb'

# Colors
color0='#0A0101'
color1='#B32C2C'
color2='#CC0202'
color3='#F40301'
color4='#E62D1B'
color5='#E65930'
color6='#F7B242'
color7='#ddd2cb'
color8='#9a938e'
color9='#B32C2C'
color10='#CC0202'
color11='#F40301'
color12='#E62D1B'
color13='#E65930'
color14='#F7B242'
color15='#ddd2cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
