# Shell variables
# Generated by 'wal'
wallpaper='/etc/nixos/nixos-config/Wallpaper'

# Special
background='#0c121a'
foreground='#d8c8bc'
cursor='#d8c8bc'

# Colors
color0='#0c121a'
color1='#D3A979'
color2='#697988'
color3='#987780'
color4='#58949F'
color5='#46A8AF'
color6='#62B2B1'
color7='#d8c8bc'
color8='#978c83'
color9='#D3A979'
color10='#697988'
color11='#987780'
color12='#58949F'
color13='#46A8AF'
color14='#62B2B1'
color15='#d8c8bc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
